In [2]:
import numpy as np

In [7]:
x = np.arange(10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [9]:
x = np.array([[1,2,3,4],[4,5,6,7]])
print(x)

[[1 2 3 4]
 [4 5 6 7]]


In [14]:
x = np.array([[1,2,3,4],[4,5,6,7]])
y = (x.ndim)
print(y)

2


In [15]:
y = (x.itemsize)
print(y)

4


In [16]:
y = (x.shape)
print(y)

(2, 4)


In [17]:
y = (x.reshape(4,2))
print(y)


[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [18]:
y = (x.size)
print(y)

8


In [ ]:
x = np.array([[1,2,3,4],[4,5,6,7]])
y = x

In [36]:
X = np.array([1,2,3])
y = x[2]
print(y)

tk


In [31]:
 x = np.array(["remi","tope","tk"])
 y = x[1]
 print(y)

tope


In [67]:
x = np.array([0, 1, 2, 3, 4, 5])
y = x[2:5:2]
print(y)

[2 4]


In [69]:
x = np.array([[1,2, 3, 4],[5, 6, 7, 8]])
y = X.ndim
print(y)

1


In [96]:
x = np.array([[1,2, 3, 4],[5, 6, 7, 8]])
y = x[0:1]
print(y)

[[1 2 3 4]]


In [98]:
print(" i do not understand from this point,the point where we have two dataframes")

 i do not understand from this point,the point where we have two dataframes
